package com.migsi.magicegg.enums;

public enum MagicConfigEnum {
	VERSION,
	NAME,
	FIREWORK_DELAY,
	FIREWORK_PERIOD,
	DROP_DELAY,
	START_TIME,
	IS_EVENT_RUNNING,
	REPETITION_DELAY_MIN,
	PERMISSIONS,
	OP,
	ON_START_MESSAGE,
	ON_STOP_MESSAGE,
	ON_SPAWN_MESSAGE,
	ON_DROP_MESSAGE;
}
